// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIN3JvPjpBzGxgdodmOVOwCdUBw6XnYfE',
    appId: '1:551252206501:android:86282f8e281edec25ebe4c',
    messagingSenderId: '551252206501',
    projectId: 'fir-auth-61734',
    storageBucket: 'fir-auth-61734.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk7L6pr5hUhv9j0wU0o-T5yrkh2HHmCRw',
    appId: '1:551252206501:ios:719443baf49f3d3d5ebe4c',
    messagingSenderId: '551252206501',
    projectId: 'fir-auth-61734',
    storageBucket: 'fir-auth-61734.appspot.com',
    androidClientId: '551252206501-lugp8ss9ri8ijucvvv9u0e7g8mvmo8qc.apps.googleusercontent.com',
    iosClientId: '551252206501-lglsfgofpbg9v69urqi58a4jrtagdrb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthenticationApp',
  );
}
